apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: echo-listener
spec:
  triggers:
    - binding:
        name: echo-pipeline-binding
      template:
        name: echo-pipeline-template
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: echo-pipeline-binding
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: echo-pipeline-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: consumption-monitor-run-
        labels:
          triggertemplated: "true"
          generatedBy: "echo-example"
      spec:
        pipelineRef:
          name: echo-props-pipeline
