apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-task
spec:
  steps:
    - name: simple-step
      image: ubuntu
      env:
        - name: BUILD_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/build-number']
      command: ["/bin/bash", "-c"]
      args:
        - echo -e "Start Pipeline Run";
          echo Build $BUILD_NUMBER;
    - name: show-props
      image: ubuntu
      env:
        - name: BUILD_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/build-number']
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: environment-properties
              key: env
      command: ["/bin/bash", "-c"]
      args:
        - echo -e "The \033[36menvironment\033[0m for this Step is \033[34m$ENV\033[0m";
          sleep 30;
          echo "Build $BUILD_NUMBER Complete";
