apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-task
spec:
  stepTemplate:
    stepTemplate:
    envFrom:
      - configMapRef:
          name: environment-properties
    env:
      - name: BUILD_NUMBER
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/build-number']
  steps:
    - name: simple-step
      image: ubuntu
      command: ["/bin/bash", "-c"]
      args:
        - echo -e "Start Pipeline Run";
          echo Build $BUILD_NUMBER;
    - name: show-props
      image: ubuntu
      command: ["/bin/bash", "-c"]
      args:
        - echo -e "The \033[36menvironment\033[0m for this Step is \033[34m$ENVIRONMENT\033[0m or $ENV or $environment or $env";
          sleep 30;
          echo "Build $BUILD_NUMBER Complete";
